master:
  push:
    - stages:
        - name: 安装依赖
          script:
            - npm install -g pnpm
            - pnpm install

        - name: 构建项目
          script:
            - pnpm run build

        - name: 发布到 CODING Pages
          script:
            - cd dist
          artifacts:
            - dist/**
          pages:
            publish_dir: dist
